version: '3.8'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_HOST=${DB_HOST}
  #     - DATABASE_PORT=${DB_PORT}
  #     - DATABASE_USERNAME=${DB_USER}
  #     - DATABASE_PASSWORD=${DB_PASSWORD}
  #     - DATABASE_NAME=${DB_NAME}
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - .:/app
  #     - /app/node_modules

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: